# The credentials secret will be created by the controller
apiVersion: v1
kind: Secret
metadata:
  name: "{{ norm "postmaster" .Domain }}"
  namespace: "{{ .Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Domain }}"
    app.kubernetes.io/instance: "{{ .Domain }}"
    app.kubernetes.io/component: postmaster-credentials
    app.kubernetes.io/part-of: "{{ .Domain }}"
    app.kubernetes.io/managed-by: "kube-mailserver"
stringData:
  email: "postmaster@{{ .Domain }}"
  password: "{{ .AdminPassword }}"
